### ISSUE TITLE
unable to go offline

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo#1104]
### Affected part of DeckDeckGo

- [X] Studio (online editor)

### Reproduction

Steps to reproduce:

1. Deck XHrecg3tiwhcDFWNb1Go
2. Go offline

**Comment by peterpeterparker** [comment]
@clicketyclackety I think I found the issue thanks to your example. Unsplash was not white listed anymore in our CSP rules and therefore going offline failed if such stock photos were used in a deck while trying to go offline.

I have deployed a hot fix live, this should do the trick.

If you've got 5 minutes, after a browser refresh, let me know if the issue still happen. 

<img width="1258" alt="Capture d’écran 2021-03-15 à 20 09 14" src="https://user-images.githubusercontent.com/16886711/111208789-80c23a80-85cb-11eb-840a-45173ab1aec5.png">

**Comment by clicketyclackety** [comment]
I tried this, had no luck, emptied cookies cache etc, but still the same error on chrome and edge :(

**Comment by peterpeterparker** [comment]
@clicketyclackety a pity. can you open your console debugger and see if any error is printed out? if yes, can you provide a screenshot?

**Comment by clicketyclackety** [comment]
Hey @peterpeterparker, I turned on verbose in the chrome debugger and I get 0 output messages sorry!

**Comment by peterpeterparker** [comment]
@clicketyclackety should be good now, I  detecteed something else and I have added one more features. Hope  it works with it 😅

Thank you for the help!

**Comment by clicketyclackety** [comment]
I seem to be able to go offline! :100:
Thanks so much @peterpeterparker!

**Comment by peterpeterparker** [comment]
Woooohooooo that's great to hear 🥳
Thanks again for the issue and help!
